apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml
  - ingress-www-redirect.yaml
images:
  - name: registry.144.91.77.245.sslip.io/homelendingadvisor
    newTag: f4c8b2505466341e90e52684c2df08dc33f1956c
